import {ApplicationLicensesTabTriggerView as CEApplicationLicensesTabTriggerView} from "@ce-internal/application/views/ApplicationLicensesTabTriggerView"

export const ApplicationLicensesTabTriggerView = CEApplicationLicensesTabTriggerView
